/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.vinicius;

import br.com.vinicius.objeto.Grupo;
import br.com.vinicius.objeto.Peixe;
import br.com.vinicius.objeto.Zoologico;
import java.text.SimpleDateFormat;
import javafx.scene.chart.PieChart.Data;
import javax.swing.JOptionPane;

/**
 *
 * @author vinicius.132217
 */
public class TelaAnimal extends javax.swing.JFrame {

    Zoologico z = new Zoologico(WIDTH);

    void desabilitaLobo() {
        this.jTFPeso.setEnabled(false);
        this.jTFTamanho.setEnabled(false);
        this.jTFDatadeNascimento.setEnabled(false);
    }

    void desabilitaPeixe() {
        this.jTFTipo.setEnabled(false);
    }

    void abilitarLobo() {
        this.jTFPeso.setEnabled(true);
        this.jTFTamanho.setEnabled(true);
        this.jTFDatadeNascimento.setEnabled(true);
    }

    void abilitaPeixe() {
        this.jTFTipo.setEnabled(true);
    }

    /**
     * Creates new form TelaAnimal
     */
    public TelaAnimal() {
        initComponents();
        desabilitaLobo();
        desabilitaPeixe();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLTitulo = new javax.swing.JLabel();
        jPAnimal = new javax.swing.JPanel();
        jLAnimais = new javax.swing.JLabel();
        jLDescricao = new javax.swing.JLabel();
        jLStatus = new javax.swing.JLabel();
        jTFDescricao = new javax.swing.JTextField();
        jTFStatus = new javax.swing.JTextField();
        jPGrupo = new javax.swing.JPanel();
        jLNome = new javax.swing.JLabel();
        jLDescricao1 = new javax.swing.JLabel();
        jTFNome = new javax.swing.JTextField();
        jTFDescricaoGrupo = new javax.swing.JTextField();
        jLGrupos = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLLobo = new javax.swing.JLabel();
        jLPeso = new javax.swing.JLabel();
        jLTamanho = new javax.swing.JLabel();
        jLDatadeNascimento = new javax.swing.JLabel();
        jTFPeso = new javax.swing.JTextField();
        jTFTamanho = new javax.swing.JTextField();
        jTFDatadeNascimento = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLPeixe = new javax.swing.JLabel();
        jLTipo = new javax.swing.JLabel();
        jTFTipo = new javax.swing.JTextField();
        jBCadastro = new javax.swing.JButton();
        jBConsutaCadastro = new javax.swing.JButton();
        jRBLobo = new javax.swing.JRadioButton();
        jRBPeixe = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLTitulo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLTitulo.setText("Cadastro de animais");

        jPAnimal.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 51, 0)));

        jLAnimais.setText("Animais");

        jLDescricao.setText("Descrição");

        jLStatus.setText("Status");

        jTFDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFDescricaoActionPerformed(evt);
            }
        });

        jTFStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPAnimalLayout = new javax.swing.GroupLayout(jPAnimal);
        jPAnimal.setLayout(jPAnimalLayout);
        jPAnimalLayout.setHorizontalGroup(
            jPAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAnimalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLDescricao)
                    .addComponent(jLStatus)
                    .addComponent(jTFStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPAnimalLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLAnimais)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPAnimalLayout.setVerticalGroup(
            jPAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAnimalLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLAnimais)
                .addGap(18, 18, 18)
                .addComponent(jLDescricao)
                .addGap(13, 13, 13)
                .addComponent(jTFDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTFStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPGrupo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 51, 0)));

        jLNome.setText("Nome");

        jLDescricao1.setText("Descrição");

        jLGrupos.setText("Grupos");

        javax.swing.GroupLayout jPGrupoLayout = new javax.swing.GroupLayout(jPGrupo);
        jPGrupo.setLayout(jPGrupoLayout);
        jPGrupoLayout.setHorizontalGroup(
            jPGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPGrupoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLNome)
                    .addComponent(jLDescricao1)
                    .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFDescricaoGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPGrupoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLGrupos)
                .addGap(88, 88, 88))
        );
        jPGrupoLayout.setVerticalGroup(
            jPGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPGrupoLayout.createSequentialGroup()
                .addComponent(jLGrupos)
                .addGap(17, 17, 17)
                .addComponent(jLNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLDescricao1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFDescricaoGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));

        jLLobo.setText("Lobo");

        jLPeso.setText("peso");

        jLTamanho.setText("Tamanho");

        jLDatadeNascimento.setText("Data de nascimento");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLPeso))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLDatadeNascimento))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLTamanho))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTFTamanho, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                            .addComponent(jTFPeso)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTFDatadeNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLLobo)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLLobo)
                .addGap(12, 12, 12)
                .addComponent(jLPeso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLTamanho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLDatadeNascimento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFDatadeNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));

        jLPeixe.setText("Peixe");

        jLTipo.setText("Tipo");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLPeixe))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLTipo))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTFTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLPeixe)
                .addGap(18, 18, 18)
                .addComponent(jLTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 35, Short.MAX_VALUE))
        );

        jBCadastro.setText("Cadastro");
        jBCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastroActionPerformed(evt);
            }
        });

        jBConsutaCadastro.setText("Consutar o Cadastro");
        jBConsutaCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsutaCadastroActionPerformed(evt);
            }
        });

        jRBLobo.setText("Lobo");
        jRBLobo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBLoboActionPerformed(evt);
            }
        });

        jRBPeixe.setText("Peixe");
        jRBPeixe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBPeixeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jBConsutaCadastro))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(jBCadastro)))))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRBLobo)
                    .addComponent(jRBPeixe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPGrupo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jRBLobo)
                        .addGap(36, 36, 36)
                        .addComponent(jRBPeixe)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jBCadastro)
                                .addGap(39, 39, 39)
                                .addComponent(jBConsutaCadastro)
                                .addGap(43, 43, 43))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFStatusActionPerformed

    private void jTFDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFDescricaoActionPerformed

    private void jRBLoboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBLoboActionPerformed
        if (jRBPeixe.isSelected()) {
            desabilitaPeixe();
        }
        abilitarLobo();

    }//GEN-LAST:event_jRBLoboActionPerformed

    private void jRBPeixeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBPeixeActionPerformed
        if (jRBLobo.isSelected()) {
            desabilitaLobo();
        }
        abilitaPeixe();
    }//GEN-LAST:event_jRBPeixeActionPerformed

    private void jBCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastroActionPerformed
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        if (jRBLobo.isSelected()) {
            String descriAnimal, nome, descriGrupo, tipo;
            int peso, tamanho;
            Data datadenasc;

            descriAnimal = jTFDescricao.getText();
            nome = jTFNome.getText();
            descriGrupo = jTFDescricaoGrupo.getName();
            tipo = jTFTipo.getText();
            peso=Integer.parseInt(jTFPeso.getText());
            tamanho=Integer.parseInt(jTFTamanho.getText());
            datadenasc= sdf.parse(jTFDatadeNascimento.getText());

        } else if (jRBPeixe.isSelected()) {
            String descriAnimal, nome, descriGrupo, tipo;
            char status = ' ';

            descriAnimal = jTFDescricao.getText();
            nome = jTFNome.getText();
            descriGrupo = jTFDescricaoGrupo.getName();
            tipo = jTFTipo.getText();

            try {
                status = jTFStatus.getText().toUpperCase().charAt(0);
            } catch (StringIndexOutOfBoundsException sioobe) {
                JOptionPane.showMessageDialog(this, sioobe);
            }
            z.getAnimais().add(new Peixe(tipo, WIDTH, new Grupo(nome, descriGrupo), descriAnimal, status));
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, insererir umas das opçoes de animal(peixe ou lobo)");
        }
    }//GEN-LAST:event_jBCadastroActionPerformed

    private void jBConsutaCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsutaCadastroActionPerformed
        JOptionPane.showMessageDialog(this, z.toString());
    }//GEN-LAST:event_jBConsutaCadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAnimal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadastro;
    private javax.swing.JButton jBConsutaCadastro;
    private javax.swing.JLabel jLAnimais;
    private javax.swing.JLabel jLDatadeNascimento;
    private javax.swing.JLabel jLDescricao;
    private javax.swing.JLabel jLDescricao1;
    private javax.swing.JLabel jLGrupos;
    private javax.swing.JLabel jLLobo;
    private javax.swing.JLabel jLNome;
    private javax.swing.JLabel jLPeixe;
    private javax.swing.JLabel jLPeso;
    private javax.swing.JLabel jLStatus;
    private javax.swing.JLabel jLTamanho;
    private javax.swing.JLabel jLTipo;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JPanel jPAnimal;
    private javax.swing.JPanel jPGrupo;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRBLobo;
    private javax.swing.JRadioButton jRBPeixe;
    private javax.swing.JTextField jTFDatadeNascimento;
    private javax.swing.JTextField jTFDescricao;
    private javax.swing.JTextField jTFDescricaoGrupo;
    private javax.swing.JTextField jTFNome;
    private javax.swing.JTextField jTFPeso;
    private javax.swing.JTextField jTFStatus;
    private javax.swing.JTextField jTFTamanho;
    private javax.swing.JTextField jTFTipo;
    // End of variables declaration//GEN-END:variables
}
